name: JamahlDotCom
analytics: {}
purpose:
  - type: contact
    url: 'tel:646.705.5582'
    label: CONTACT
github: true
description: SAG-AFTRA-AEA
cta:
  bucket: null
  version: null
  domain: null
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.4421209892572485
color:
  lightness: 0.2267870440791444
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  saturation: 0.4069286212288212
  brandStrength: 0.1002253752174133
  rhythmicContrast: 0.1932895418543295
content_rating:
  adult: false
typography_spectrum: 0.4840872590178347
opengraph: {}
title: Jamahl Garrison-Lowe
